// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MultiplyServiceClient is the client API for MultiplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplyServiceClient interface {
	Multiply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type multiplyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplyServiceClient(cc grpc.ClientConnInterface) MultiplyServiceClient {
	return &multiplyServiceClient{cc}
}

func (c *multiplyServiceClient) Multiply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.multiply.v1.MultiplyService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplyServiceServer is the server API for MultiplyService service.
// All implementations must embed UnimplementedMultiplyServiceServer
// for forward compatibility
type MultiplyServiceServer interface {
	Multiply(context.Context, *Request) (*Result, error)
	mustEmbedUnimplementedMultiplyServiceServer()
}

// UnimplementedMultiplyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMultiplyServiceServer struct {
}

func (UnimplementedMultiplyServiceServer) Multiply(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedMultiplyServiceServer) mustEmbedUnimplementedMultiplyServiceServer() {}

// UnsafeMultiplyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplyServiceServer will
// result in compilation errors.
type UnsafeMultiplyServiceServer interface {
	mustEmbedUnimplementedMultiplyServiceServer()
}

func RegisterMultiplyServiceServer(s grpc.ServiceRegistrar, srv MultiplyServiceServer) {
	s.RegisterService(&MultiplyService_ServiceDesc, srv)
}

func _MultiplyService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplyServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.multiply.v1.MultiplyService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplyServiceServer).Multiply(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiplyService_ServiceDesc is the grpc.ServiceDesc for MultiplyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiplyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.multiply.v1.MultiplyService",
	HandlerType: (*MultiplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _MultiplyService_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/protov1/multiply.proto",
}
